version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kudos
    ports:
      - "8081:80"
    volumes:
      - ./kudos:/var/www/html
    networks:
      - webnet
    entrypoint: ["/bin/sh", "-c",  "apache2-foreground"]

  db:
    image: mysql:8.0
    container_name: kudos_db
    ports:
      - "3308:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kudos_db
      MYSQL_USER: kudos_user
      MYSQL_PASSWORD: kudos_password
    volumes:
      - ./kudos/db_data:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kudos_phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: kudos_db
      PMA_PORT: 3306
      PMA_USER: kudos_user
      PMA_PASSWORD: kudos_password
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
